# Generated by Django 3.1.7 on 2021-02-27 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210228_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits allowed.', regex='^[9|8|7|6]\\d{9}')]),
        ),
    ]
